version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project02-server
    container_name: project02-server
    ports:
      - "8090:8080"
    env_file:
      - ./env
    volumes:
      - /Users/lsh/Documents/config/grafana/log:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:latest