spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/project02?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: redis
  port: 6379
