spring:
  profiles:
    group:
      "local": "local, actuator, weather"
      "default": "local, actuator, weather"
      "product": "product, actuator, weather"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100


