spring:
  profiles:
    group:
      "local": "local, actuator, weather, oauth"
      "default": "local, actuator, weather, oauth"
      "product": "product, actuator, weather, oauth"

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100