spring:
  profiles:
    group:
      "local": "local, actuator"
      "default": "local, actuator"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        default_batch_fetch_size: 100

logging:
  file:
    name: /Users/lsh/Documents/config/grafana/log/project02.log


