name: test before merging


on:
  push:
    branches:
        - test
#  pull_request:
#    branches:
#      - develop
#      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test -i